version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      - elasticsearch
    restart: always

  gobgp:
    image: osrg/gobgp
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - 179:179
      - 179:179/udp
    expose:
      - 50051
    entrypoint: /go/bin/gobgpd -f /root/gobgpd.yml
    volumes:
      - ./gobgpd.yml:/root/gobgpd.yml

  daemon:
    build: daemon
    depends_on:
      - elasticsearch
      - gobgp
    restart: always

  server:
    build: server
    expose:
      - 8080
    depends_on:
      - elasticsearch
    restart: always

  front:
    build: front
    ports:
      - 3000:3000
    depends_on:
      - server
    restart: always
